### ISSUE TITLE
Does not work with touch events

### ISSUE THREAD

**Issue by nathanheffley** [ErlendEllingsen/pull-to-reload#2] opened 2017-03-03 16:05 UTC
From my testing (which was not extensive but it was performed in emulation and on my real phone) the touch functionality of this script does not work, even with the jQuery version.

In my pull request to remove jQuery I just left out the touch events all together which is why you may not see the touch events if that's merged in by the time you read this.

**Comment by ErlendEllingsen** [comment] 2017-03-04 14:20
I have tested this on iOS-emulator and on iOS-device and it works as expected. When removing the touch-events the plugin stops working as intended. 

I merged your PR without properly analysing the content. I therefore re-added the touch events accordingly.

**Comment by ErlendEllingsen** [comment] 2017-03-05 13:15
Bug confirmed. Did not function on Android & Chrome browsers. Just published version 1.1 that resolved this. Care to confirm before I close this test - @NathanHeffley ? 🌴

**Comment by ErlendEllingsen** [comment] 2017-03-05 14:19
Closing this issue. Resolved by https://github.com/ErlendEllingsen/pull-to-reload/commit/835337a65f3f81ef62e237fe24e3c1bf723d6c88

**Closed as completed by ErlendEllingsen** 2017-03-05 14:19 UTC
